"""rename department

Revision ID: 24a9b3e18137
Revises: 8cd0ad3ca97b
Create Date: 2024-06-30 10:06:48.163609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a9b3e18137'
down_revision = '8cd0ad3ca97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
